package com.Scorpio.RsaH.configuration;

import java.io.File;
import java.util.logging.Level;

import net.minecraftforge.common.Configuration;

import com.Scorpio.RsaH.lib.BlockIDs;
import com.Scorpio.RsaH.lib.ItemIDs;
import com.Scorpio.RsaH.lib.Reference;
import com.Scorpio.RsaH.lib.Strings;

import cpw.mods.fml.common.FMLLog;

public class ConfigurationHandler
{
	public static Configuration config;
	
	public static void init(File file)
	{
		config = new Configuration(file);
		
		try
		{
			config.load();
			
			/**
			 * Block Configuration
			 */
			BlockIDs.BLOCK_BLUESTONE_ID = config.getBlock(Strings.BLOCK_BLUESTONE_NAME, BlockIDs.BLOCK_BLUESTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_BLUESTONE_ID_DEFAULT);
			BlockIDs.BLOCK_BLACKSTONE_ID = config.getBlock(Strings.BLOCK_BLACKSTONE_NAME, BlockIDs.BLOCK_BLACKSTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_BLACKSTONE_ID_DEFAULT);
			BlockIDs.BLOCK_BROWNSTONE_ID = config.getBlock(Strings.BLOCK_BROWNSTONE_NAME, BlockIDs.BLOCK_BROWNSTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_BROWNSTONE_ID_DEFAULT);
			BlockIDs.BLOCK_CYANSTONE_ID = config.getBlock(Strings.BLOCK_CYANSTONE_NAME, BlockIDs.BLOCK_CYANSTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_CYANSTONE_ID_DEFAULT);
			BlockIDs.BLOCK_GLOWSTONE_ID = config.getBlock(Strings.BLOCK_GLOWSTONE_NAME, BlockIDs.BLOCK_GLOWSTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_GLOWSTONE_ID_DEFAULT);
			BlockIDs.BLOCK_GREYSTONE_ID = config.getBlock(Strings.BLOCK_GRAYSTONE_NAME, BlockIDs.BLOCK_GREYSTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_GREYSTONE_ID_DEFAULT);
			BlockIDs.BLOCK_GREENSTONE_ID = config.getBlock(Strings.BLOCK_GREENSTONE_NAME, BlockIDs.BLOCK_GREENSTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_GREENSTONE_ID_DEFAULT);
			BlockIDs.BLOCK_LIGHTBLUESTONE_ID = config.getBlock(Strings.BLOCK_LIGHTBLUESTONE_NAME, BlockIDs.BLOCK_LIGHTBLUESTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_LIGHTBLUESTONE_ID_DEFAULT);
			BlockIDs.BLOCK_LIGHTGRAYSTONE_ID = config.getBlock(Strings.BLOCK_LIGHTGRAYSTONE_NAME, BlockIDs.BLOCK_LIGHTGRAYSTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_LIGHTGRAYSTONE_ID_DEFAULT);
			BlockIDs.BLOCK_LIMEGREENSTONE_ID = config.getBlock(Strings.BLOCK_LIMEGREENSTONE_NAME, BlockIDs.BLOCK_LIMEGREENSTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_LIMEGREENSTONE_ID_DEFAULT);
			BlockIDs.BLOCK_MAGENTASTONE_ID = config.getBlock(Strings.BLOCK_MAGENTASTONE_NAME, BlockIDs.BLOCK_MAGENTASTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_MAGENTASTONE_ID_DEFAULT);
			BlockIDs.BLOCK_ORANGESTONE_ID = config.getBlock(Strings.BLOCK_ORANGESTONE_NAME, BlockIDs.BLOCK_ORANGESTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_ORANGESTONE_ID_DEFAULT);
			BlockIDs.BLOCK_PINKSTONE_ID = config.getBlock(Strings.BLOCK_PINKSTONE_NAME, BlockIDs.BLOCK_PINKSTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_PINKSTONE_ID_DEFAULT);
			BlockIDs.BLOCK_PURPLESTONE_ID = config.getBlock(Strings.BLOCK_PURPLESTONE_NAME, BlockIDs.BLOCK_PURPLESTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_PURPLESTONE_ID_DEFAULT);
			BlockIDs.BLOCK_WHITESTONE_ID = config.getBlock(Strings.BLOCK_WHITESTONE_NAME, BlockIDs.BLOCK_WHITESTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_WHITESTONE_ID_DEFAULT);
			BlockIDs.BLOCK_YELLOWSTONE_ID = config.getBlock(Strings.BLOCK_YELLOWSTONE_NAME, BlockIDs.BLOCK_YELLOWSTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_YELLOWSTONE_ID_DEFAULT);
			BlockIDs.BLOCK_MAGMASTONE_ID = config.getBlock(Strings.BLOCK_MAGMASTONE_NAME, BlockIDs.BLOCK_MAGMASTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_MAGMASTONE_ID_DEFAULT);
			BlockIDs.BLOCK_STRANGESTONE_ID = config.getBlock(Strings.BLOCK_STRANGESTONE_NAME, BlockIDs.BLOCK_STRANGESTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_STRANGESTONE_ID_DEFAULT);
			
			/**
			 * Block-Wire Configuration
			 */
			BlockIDs.BLOCK_WIRE_BLUESTONE_ID = config.getBlock(Strings.BLOCK_WIRE_BLUESTONE_NAME, BlockIDs.BLOCK_WIRE_BLUESTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_WIRE_BLUESTONE_ID_DEFAULT);
			BlockIDs.BLOCK_WIRE_BLACKSTONE_ID = config.getBlock(Strings.BLOCK_WIRE_BLACKSTONE_NAME, BlockIDs.BLOCK_WIRE_BLACKSTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_WIRE_BLACKSTONE_ID_DEFAULT);
			BlockIDs.BLOCK_WIRE_BROWNSTONE_ID = config.getBlock(Strings.BLOCK_WIRE_BROWNSTONE_NAME, BlockIDs.BLOCK_WIRE_BROWNSTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_WIRE_BROWNSTONE_ID_DEFAULT);
			BlockIDs.BLOCK_WIRE_CYANSTONE_ID = config.getBlock(Strings.BLOCK_WIRE_CYANSTONE_NAME, BlockIDs.BLOCK_WIRE_CYANSTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_WIRE_CYANSTONE_ID_DEFAULT);
			BlockIDs.BLOCK_WIRE_GLOWSTONE_ID = config.getBlock(Strings.BLOCK_WIRE_GLOWSTONE_NAME, BlockIDs.BLOCK_WIRE_GLOWSTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_WIRE_GLOWSTONE_ID_DEFAULT);
			BlockIDs.BLOCK_WIRE_GRAYSTONE_ID = config.getBlock(Strings.BLOCK_WIRE_GRAYSTONE_NAME, BlockIDs.BLOCK_WIRE_GRAYSTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_WIRE_GRAYSTONE_ID_DEFAULT);
			BlockIDs.BLOCK_WIRE_GREENSTONE_ID = config.getBlock(Strings.BLOCK_WIRE_GREENSTONE_NAME, BlockIDs.BLOCK_WIRE_GREENSTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_WIRE_GREENSTONE_ID_DEFAULT);
			BlockIDs.BLOCK_WIRE_LIGHTBLUESTONE_ID = config.getBlock(Strings.BLOCK_WIRE_LIGHTBLUESTONE_NAME, BlockIDs.BLOCK_WIRE_LIGHTBLUESTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_WIRE_LIGHTBLUESTONE_ID_DEFAULT);
			BlockIDs.BLOCK_WIRE_LIGHTGRAYSTONE_ID = config.getBlock(Strings.BLOCK_WIRE_LIGHTGRAYSTONE_NAME, BlockIDs.BLOCK_WIRE_LIGHTGRAYSTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_WIRE_LIGHTGRAYSTONE_ID_DEFAULT);
			BlockIDs.BLOCK_WIRE_LIMEGREENSTONE_ID = config.getBlock(Strings.BLOCK_WIRE_LIMEGREENSTONE_NAME, BlockIDs.BLOCK_WIRE_LIMEGREENSTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_WIRE_LIMEGREENSTONE_ID_DEFAULT);
			BlockIDs.BLOCK_WIRE_MAGENTASTONE_ID = config.getBlock(Strings.BLOCK_WIRE_MAGENTASTONE_NAME, BlockIDs.BLOCK_WIRE_MAGENTASTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_WIRE_MAGENTASTONE_ID_DEFAULT);
			BlockIDs.BLOCK_WIRE_ORANGESTONE_ID = config.getBlock(Strings.BLOCK_WIRE_ORANGESTONE_NAME, BlockIDs.BLOCK_WIRE_ORANGESTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_WIRE_ORANGESTONE_ID_DEFAULT);
			BlockIDs.BLOCK_WIRE_PINKSTONE_ID = config.getBlock(Strings.BLOCK_WIRE_PINKSTONE_NAME, BlockIDs.BLOCK_WIRE_PINKSTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_WIRE_PINKSTONE_ID_DEFAULT);
			BlockIDs.BLOCK_WIRE_PURPLESTONE_ID = config.getBlock(Strings.BLOCK_WIRE_PURPLESTONE_NAME, BlockIDs.BLOCK_WIRE_PURPLESTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_WIRE_PURPLESTONE_ID_DEFAULT);
			BlockIDs.BLOCK_WIRE_WHITESTONE_ID = config.getBlock(Strings.BLOCK_WIRE_WHITESTONE_NAME, BlockIDs.BLOCK_WIRE_WHITESTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_WIRE_WHITESTONE_ID_DEFAULT);
			BlockIDs.BLOCK_WIRE_YELLOWSTONE_ID = config.getBlock(Strings.BLOCK_WIRE_YELLOWSTONE_NAME, BlockIDs.BLOCK_WIRE_YELLOWSTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_WIRE_YELLOWSTONE_ID_DEFAULT);
			BlockIDs.BLOCK_WIRE_MAGMASTONE_ID = config.getBlock(Strings.BLOCK_WIRE_MAGMASTONE_NAME, BlockIDs.BLOCK_WIRE_MAGMASTONE_ID_DEFAULT).getInt(BlockIDs.BLOCK_WIRE_MAGMASTONE_ID_DEFAULT);
			
			/**
			 * Block-Torch Configuration
			 */
			BlockIDs.BLOCK_TORCH_BLUESTONEIDLE_ID = config.getBlock(Strings.BLOCK_TORCH_BLUESTONE2_NAME, BlockIDs.BLOCK_TORCH_BLUESTONEIDLE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_BLUESTONEIDLE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_BLUESTONEACTIVE_ID = config.getBlock(Strings.BLOCK_TORCH_BLUESTONE_NAME, BlockIDs.BLOCK_TORCH_BLUESTONEACTIVE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_BLUESTONEACTIVE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_BLACKSTONEIDLE_ID = config.getBlock(Strings.BLOCK_TORCH_BLACKSTONE2_NAME, BlockIDs.BLOCK_TORCH_BLACKSTONEIDLE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_BLACKSTONEIDLE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_BLACKSTONEACTIVE_ID = config.getBlock(Strings.BLOCK_TORCH_BLACKSTONE_NAME, BlockIDs.BLOCK_TORCH_BLACKSTONEACTIVE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_BLACKSTONEACTIVE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_BROWNSTONEIDLE_ID = config.getBlock(Strings.BLOCK_TORCH_BROWNSTONE2_NAME, BlockIDs.BLOCK_TORCH_BROWNSTONEIDLE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_BROWNSTONEIDLE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_BROWNSTONEACTIVE_ID = config.getBlock(Strings.BLOCK_TORCH_BROWNSTONE_NAME, BlockIDs.BLOCK_TORCH_BROWNSTONEACTIVE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_BROWNSTONEACTIVE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_CYANSTONEIDLE_ID = config.getBlock(Strings.BLOCK_TORCH_CYANSTONE2_NAME, BlockIDs.BLOCK_TORCH_CYANSTONEIDLE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_CYANSTONEIDLE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_CYANSTONEACTIVE_ID = config.getBlock(Strings.BLOCK_TORCH_CYANSTONE_NAME, BlockIDs.BLOCK_TORCH_CYANSTONEACTIVE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_CYANSTONEACTIVE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_GLOWSTONEIDLE_ID = config.getBlock(Strings.BLOCK_TORCH_GLOWSTONE2_NAME, BlockIDs.BLOCK_TORCH_GLOWSTONEIDLE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_GLOWSTONEIDLE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_GLOWSTONEACTIVE_ID = config.getBlock(Strings.BLOCK_TORCH_GLOWSTONE_NAME, BlockIDs.BLOCK_TORCH_GLOWSTONEACTIVE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_GLOWSTONEACTIVE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_GRAYSTONEIDLE_ID = config.getBlock(Strings.BLOCK_TORCH_GRAYSTONE2_NAME, BlockIDs.BLOCK_TORCH_GRAYSTONEIDLE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_GRAYSTONEIDLE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_GRAYSTONEACTIVE_ID = config.getBlock(Strings.BLOCK_TORCH_GRAYSTONE_NAME, BlockIDs.BLOCK_TORCH_GRAYSTONEACTIVE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_GRAYSTONEACTIVE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_GREENSTONEIDLE_ID = config.getBlock(Strings.BLOCK_TORCH_GREENSTONE2_NAME, BlockIDs.BLOCK_TORCH_GREENSTONEIDLE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_GREENSTONEIDLE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_GREENSTONEACTIVE_ID = config.getBlock(Strings.BLOCK_TORCH_GREENSTONE_NAME, BlockIDs.BLOCK_TORCH_GREENSTONEACTIVE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_GREENSTONEACTIVE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_LIGHTBLUESTONEIDLE_ID = config.getBlock(Strings.BLOCK_TORCH_LIGHTBLUESTONE2_NAME, BlockIDs.BLOCK_TORCH_LIGHTBLUESTONEIDLE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_LIGHTBLUESTONEIDLE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_LIGHTBLUESTONEACTIVE_ID = config.getBlock(Strings.BLOCK_TORCH_LIGHTBLUESTONE_NAME, BlockIDs.BLOCK_TORCH_LIGHTBLUESTONEACTIVE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_LIGHTBLUESTONEACTIVE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_LIGHTGRAYSTONEIDLE_ID = config.getBlock(Strings.BLOCK_TORCH_LIGHTGRAYSTONE2_NAME, BlockIDs.BLOCK_TORCH_LIGHTGRAYSTONEIDLE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_LIGHTGRAYSTONEIDLE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_LIGHTGRAYSTONEACTIVE_ID = config.getBlock(Strings.BLOCK_TORCH_LIGHTGRAYSTONE_NAME, BlockIDs.BLOCK_TORCH_LIGHTGRAYSTONEACTIVE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_LIGHTGRAYSTONEACTIVE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_LIMEGREENSTONEIDLE_ID = config.getBlock(Strings.BLOCK_TORCH_LIMEGREENSTONE2_NAME, BlockIDs.BLOCK_TORCH_LIMEGREENSTONEIDLE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_LIMEGREENSTONEIDLE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_LIMEGREENSTONEACTIVE_ID = config.getBlock(Strings.BLOCK_TORCH_LIMEGREENSTONE_NAME, BlockIDs.BLOCK_TORCH_LIMEGREENSTONEACTIVE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_LIMEGREENSTONEACTIVE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_MAGENTASTONEIDLE_ID = config.getBlock(Strings.BLOCK_TORCH_MAGENTASTONE2_NAME, BlockIDs.BLOCK_TORCH_MAGENTASTONEIDLE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_MAGENTASTONEIDLE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_MAGENTASTONEACTIVE_ID = config.getBlock(Strings.BLOCK_TORCH_MAGENTASTONE_NAME, BlockIDs.BLOCK_TORCH_MAGENTASTONEACTIVE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_MAGENTASTONEACTIVE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_MAGMASTONEIDLE_ID = config.getBlock(Strings.BLOCK_TORCH_MAGMASTONE2_NAME, BlockIDs.BLOCK_TORCH_MAGMASTONEIDLE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_MAGMASTONEIDLE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_MAGMASTONEACTIVE_ID = config.getBlock(Strings.BLOCK_TORCH_MAGMASTONE_NAME, BlockIDs.BLOCK_TORCH_MAGMASTONEACTIVE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_MAGMASTONEACTIVE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_ORANGESTONEIDLE_ID = config.getBlock(Strings.BLOCK_TORCH_ORANGESTONE2_NAME, BlockIDs.BLOCK_TORCH_ORANGESTONEIDLE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_ORANGESTONEIDLE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_ORANGESTONEACTIVE_ID = config.getBlock(Strings.BLOCK_TORCH_ORANGESTONE_NAME, BlockIDs.BLOCK_TORCH_ORANGESTONEACTIVE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_ORANGESTONEACTIVE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_PINKSTONEIDLE_ID = config.getBlock(Strings.BLOCK_TORCH_PINKSTONE2_NAME, BlockIDs.BLOCK_TORCH_PINKSTONEIDLE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_PINKSTONEIDLE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_PINKSTONEACTIVE_ID = config.getBlock(Strings.BLOCK_TORCH_PINKSTONE_NAME, BlockIDs.BLOCK_TORCH_PINKSTONEACTIVE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_PINKSTONEACTIVE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_PURPLESTONEIDLE_ID = config.getBlock(Strings.BLOCK_TORCH_PURPLESTONE2_NAME, BlockIDs.BLOCK_TORCH_PURPLESTONEIDLE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_PURPLESTONEIDLE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_PURPLESTONEACTIVE_ID = config.getBlock(Strings.BLOCK_TORCH_PURPLESTONE_NAME, BlockIDs.BLOCK_TORCH_PURPLESTONEACTIVE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_PURPLESTONEACTIVE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_WHITESTONEIDLE_ID = config.getBlock(Strings.BLOCK_TORCH_WHITESTONE2_NAME, BlockIDs.BLOCK_TORCH_WHITESTONEIDLE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_WHITESTONEIDLE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_WHITESTONEACTIVE_ID = config.getBlock(Strings.BLOCK_TORCH_WHITESTONE_NAME, BlockIDs.BLOCK_TORCH_WHITESTONEACTIVE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_WHITESTONEACTIVE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_YELLOWSTONEIDLE_ID = config.getBlock(Strings.BLOCK_TORCH_YELLOWSTONE2_NAME, BlockIDs.BLOCK_TORCH_YELLOWSTONEIDLE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_YELLOWSTONEIDLE_ID_DEFAULT);
			BlockIDs.BLOCK_TORCH_YELLOWSTONEACTIVE_ID = config.getBlock(Strings.BLOCK_TORCH_YELLOWSTONE_NAME, BlockIDs.BLOCK_TORCH_YELLOWSTONEACTIVE_ID_DEFAULT).getInt(BlockIDs.BLOCK_TORCH_YELLOWSTONEACTIVE_ID_DEFAULT);
			
			/**
			 * Item Configuration
			 */
			ItemIDs.ITEM_DUST_BLUESTONE_ID = config.getItem(Strings.ITEM_DUST_BLUESTONE_NAME, ItemIDs.ITEM_DUST_BLUESTONE_ID_DEFAULT).getInt(ItemIDs.ITEM_DUST_BLUESTONE_ID_DEFAULT);
			ItemIDs.ITEM_DUST_BLACKSTONE_ID = config.getItem(Strings.ITEM_DUST_BLACKSTONE_NAME, ItemIDs.ITEM_DUST_BLACKSTONE_ID_DEFAULT).getInt(ItemIDs.ITEM_DUST_BLACKSTONE_ID_DEFAULT);
			ItemIDs.ITEM_DUST_BROWNSTONE_ID = config.getItem(Strings.ITEM_DUST_BROWNSTONE_NAME, ItemIDs.ITEM_DUST_BROWNSTONE_ID_DEFAULT).getInt(ItemIDs.ITEM_DUST_BROWNSTONE_ID_DEFAULT);
			ItemIDs.ITEM_DUST_CYANSTONE_ID = config.getItem(Strings.ITEM_DUST_CYANSTONE_NAME, ItemIDs.ITEM_DUST_CYANSTONE_ID_DEFAULT).getInt(ItemIDs.ITEM_DUST_CYANSTONE_ID_DEFAULT);
			ItemIDs.ITEM_DUST_GLOWSTONE_ID = config.getItem(Strings.ITEM_DUST_GLOWSTONE_NAME, ItemIDs.ITEM_DUST_GLOWSTONE_ID_DEFAULT).getInt(ItemIDs.ITEM_DUST_GLOWSTONE_ID_DEFAULT);
			ItemIDs.ITEM_DUST_GRAYSTONE_ID = config.getItem(Strings.ITEM_DUST_GRAYSTONE_NAME, ItemIDs.ITEM_DUST_GRAYSTONE_ID_DEFAULT).getInt(ItemIDs.ITEM_DUST_GRAYSTONE_ID_DEFAULT);
			ItemIDs.ITEM_DUST_GREENSTONE_ID = config.getItem(Strings.ITEM_DUST_GREENSTONE_NAME, ItemIDs.ITEM_DUST_GREENSTONE_ID_DEFAULT).getInt(ItemIDs.ITEM_DUST_GREENSTONE_ID_DEFAULT);
			ItemIDs.ITEM_DUST_LIGHTBLUESTONE_ID = config.getItem(Strings.ITEM_DUST_LIGHTBLUESTONE_NAME, ItemIDs.ITEM_DUST_LIGHTBLUESTONE_ID_DEFAULT).getInt(ItemIDs.ITEM_DUST_LIGHTBLUESTONE_ID_DEFAULT);
			ItemIDs.ITEM_DUST_LIGHTGRAYSTONE_ID = config.getItem(Strings.ITEM_DUST_LIGHTGRAYSTONE_NAME, ItemIDs.ITEM_DUST_LIGHTGRAYSTONE_ID_DEFAULT).getInt(ItemIDs.ITEM_DUST_LIGHTGRAYSTONE_ID_DEFAULT);
			ItemIDs.ITEM_DUST_LIMEGREENSTONE_ID = config.getItem(Strings.ITEM_DUST_LIMEGREENSTONE_NAME, ItemIDs.ITEM_DUST_LIMEGREENSTONE_ID_DEFAULT).getInt(ItemIDs.ITEM_DUST_LIMEGREENSTONE_ID_DEFAULT);
			ItemIDs.ITEM_DUST_MAGENTASTONE_ID = config.getItem(Strings.ITEM_DUST_MAGENTASTONE_NAME, ItemIDs.ITEM_DUST_MAGENTASTONE_ID_DEFAULT).getInt(ItemIDs.ITEM_DUST_MAGENTASTONE_ID_DEFAULT);
			ItemIDs.ITEM_DUST_MAGMASTONE_ID = config.getItem(Strings.ITEM_DUST_MAGMASTONE_NAME, ItemIDs.ITEM_DUST_MAGMASTONE_ID_DEFAULT).getInt(ItemIDs.ITEM_DUST_MAGMASTONE_ID_DEFAULT);
			ItemIDs.ITEM_DUST_ORANGESTONE_ID = config.getItem(Strings.ITEM_DUST_ORANGESTONE_NAME, ItemIDs.ITEM_DUST_ORANGESTONE_ID_DEFAULT).getInt(ItemIDs.ITEM_DUST_ORANGESTONE_ID_DEFAULT);
			ItemIDs.ITEM_DUST_PINKSTONE_ID = config.getItem(Strings.ITEM_DUST_PINKSTONE_NAME, ItemIDs.ITEM_DUST_PINKSTONE_ID_DEFAULT).getInt(ItemIDs.ITEM_DUST_PINKSTONE_ID_DEFAULT);
			ItemIDs.ITEM_DUST_PURPLESTONE_ID = config.getItem(Strings.ITEM_DUST_PURPLESTONE_NAME, ItemIDs.ITEM_DUST_PURPLESTONE_ID_DEFAULT).getInt(ItemIDs.ITEM_DUST_PURPLESTONE_ID_DEFAULT);
			ItemIDs.ITEM_DUST_WHITESTONE_ID = config.getItem(Strings.ITEM_DUST_WHITESTONE_NAME, ItemIDs.ITEM_DUST_WHITESTONE_ID_DEFAULT).getInt(ItemIDs.ITEM_DUST_WHITESTONE_ID_DEFAULT);
			ItemIDs.ITEM_DUST_YELLOWSTONE_ID = config.getItem(Strings.ITEM_DUST_YELLOWSTONE_NAME, ItemIDs.ITEM_DUST_YELLOWSTONE_ID_DEFAULT).getInt(ItemIDs.ITEM_DUST_YELLOWSTONE_ID_DEFAULT);
			
		}
		catch(Exception e)
		{
			FMLLog.log(Level.SEVERE, e, Reference.MOD_ID + "Has a problem loading the cofig file!");
		}
		finally
		{
			config.save();
		}
	}
}
